version: "3.9"
services:
  web:
    container_name: age_guess_web
    build:
      context: ./
      dockerfile: Dockerfile
    
    image: age_guess_web:v1
    environment:
      - PORT=8020
    env_file:
      - .env
    ports:
      - "8001:8020"
    expose:
      - 5432
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - ./static:/app/static/
      - ./media:/app/media/
    depends_on:
      - db

  db:
    container_name: age_guess_db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

volumes:
  postgres_data: