name: Deploy on Merge Request

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku (using API Key)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku login --apikey ${{ secrets.HEROKU_API_KEY }}

      - name: Create Heroku App (if not already existing)
        run: heroku create ${{ github.repo.repo }}  # Optionally append a random string for uniqueness

      - name: Set Git Config (Optional, for future convenience)
        run: |
          git config --global url."https://api.heroku.com/".insteadOf  git@heroku.com
          git config --global url."https://heroku.com/".insteadOf  git@heroku.com  # For compatibility with older Heroku setups

      - name: Push Code to Heroku
        run: git push -f heroku HEAD:$GITHUB_HEAD_REF  # Force push (optional, use with caution)


      - name: Run Post-Deployment Tasks
        run: |
          heroku run python manage.py createsuperuser --noinput --username=admin --email=admin@example.com
          heroku run python manage.py runscript seed


          
